# Style & Quality Overrides
require: rubocop-performance

AllCops:
  Exclude:
    - 'bin/bundle'
  TargetRubyVersion: 2.3


Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/BlockLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 15
  CountKeywordArgs: true

Performance/Casecmp:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/NumericLiterals:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
